apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-website
  template:
    metadata:
      labels:
        app: php-website
    spec:
      containers:
      - name: php-website
        image: ankushramne4/new_repo:82
        imagePullPolicy: Always
        ports:
        - containerPort: 80
