apiVersion: v1
kind: Service

metadata:
  name: php-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: php-website

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP